name: py27
dependencies:
- certifi=2016.2.28=py27_0
- cycler=0.10.0=py27_0
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- icu=54.1=0
- libpng=1.6.30=1
- matplotlib=2.0.2=np113py27_0
- mkl=2017.0.3=0
- numpy=1.13.1=py27_0
- openssl=1.0.2l=0
- pandas=0.20.3=py27_0
- patsy=0.4.1=py27_0
- pip=9.0.1=py27_1
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=2
- readline=6.2=2
- scikit-learn=0.19.0=np113py27_0
- scipy=0.19.1=np113py27_0
- seaborn=0.8=py27_0
- setuptools=36.4.0=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- statsmodels=0.8.0=np113py27_0
- subprocess32=3.2.7=py27_0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - arrow==0.12.0
  - asn1crypto==0.23.0
  - attrdict==2.0.0
  - backports.functools-lru-cache==1.4
  - cachetools==2.0.1
  - cffi==1.11.2
  - chardet==3.0.4
  - cheroot==5.10.0
  - cherrypy==12.0.1
  - cryptography==2.1.4
  - enum34==1.1.6
  - future==0.16.0
  - geojson==2.3.0
  - google-auth==1.2.1
  - idna==2.6
  - ipaddress==1.0.18
  - jaraco.classes==1.4.3
  - jwcrypto==0.4.2
  - lxml==4.1.1
  - portend==2.2
  - pyasn1==0.4.2
  - pyasn1-modules==0.2.1
  - pycparser==2.18
  - pyfcm==1.4.3
  - pygeocoder==1.2.5
  - pykml==0.1.3
  - pymongo==3.5.1
  - python-crontab==2.2.7
  - requests==2.18.4
  - requests-toolbelt==0.8.0
  - rsa==3.4.2
  - tempora==1.9
  - urllib3==1.22
  - utm==0.4.2
  - xmltodict==0.11.0
